#!/bin/sh

# Set these paths appropriately

BIN="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/bin"
CMD="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/cmd"
LIB="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french-spoken.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
