#!/bin/sh

# Set these paths appropriately

BIN="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/bin"
CMD="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/cmd"
LIB="/Users/monicasen/PycharmProjects/topic-modeling/src/preprocessing/TreeTager/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english-bnc.par

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE 
